name: Update timezones

on:
  push:
    branches:
      - action-update-timezones
#   schedule:
#   - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: npm install
      run: npm install
    - name: Update timezone data
      run: grunt data:2014c
    - name: Check for changes
      id: changes
      run: git diff-index --quiet HEAD
    - name: Create Pull Request
      if: steps.changes.outputs.exit-code == 1
      uses: peter-evans/create-pull-request@v1.5.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    
